# Generated by Django 4.0.4 on 2022-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
